const process = require("process")


console.log(process.env)
// -- windows --
// {
//   ALLUSERSPROFILE: 'C:\\ProgramData',
//   ANDROID_HOME: 'C:\\Users\\Administrator\\AppData\\Local\\Android\\Sdk',
//   APPDATA: 'C:\\Users\\Administrator\\AppData\\Roaming',
//   CHROME_CRASHPAD_PIPE_NAME: '\\\\.\\pipe\\LOCAL\\crashpad_18900_AQUSRYXGVNBAADRG',
//   CommonProgramFiles: 'C:\\Program Files\\Common Files',
//   'CommonProgramFiles(x86)': 'C:\\Program Files (x86)\\Common Files',
//   CommonProgramW6432: 'C:\\Program Files\\Common Files',
//   COMPUTERNAME: 'DESKTOP-6D1598L',
//   ComSpec: 'C:\\Windows\\system32\\cmd.exe',
//   DriverData: 'C:\\Windows\\System32\\Drivers\\DriverData',
//   ELECTRON_RUN_AS_NODE: '1',
//   EPS_INSTALL_ROOT: 'c:\\program files\\sangfor\\edr\\agent\\',
//   HOMEDRIVE: 'C:',
//   HOMEPATH: '\\Users\\Administrator',
//   LOCALAPPDATA: 'C:\\Users\\Administrator\\AppData\\Local',
//   LOGONSERVER: '\\\\DESKTOP-6D1598L',
//   NUMBER_OF_PROCESSORS: '8',
//   NVM_HOME: 'C:\\Users\\Administrator\\AppData\\Roaming\\nvm',
//   NVM_SYMLINK: 'C:\\Program Files\\nodejs',
//   OneDrive: 'C:\\Users\\Administrator\\OneDrive',
//   ORIGINAL_XDG_CURRENT_DESKTOP: 'undefined',
//   OS: 'Windows_NT',
//   Path: 'C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.18.10-hotspot\\bin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\Tencent\\微信web开发者工具\\dll;%NVM_HOME%;%NVM_SYMLINK%;%PNPM_HOME%;C:\\Users\\Administrator\\AppData\\Local\\Microsoft\\WindowsApps;E:\\Microsoft VS Code\\bin;C:\\Users\\Administrator\\AppData\\Local\\Programs\\Hyper\\resources\\bin;%ANDROID_SDK_ROOT%\\platform-tools;%ANDROID_SDK_ROOT%\\emulator;%ANDROID_SDK_ROOT%\\tools;%ANDROID_SDK_ROOT%\\tools\\bin;C:\\Users\\Administrator\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs',
//   PATHEXT: '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
//   PNPM_HOME: 'C:\\Users\\Administrator\\AppData\\Local\\pnpm',
//   PROCESSOR_ARCHITECTURE: 'AMD64',
//   PROCESSOR_IDENTIFIER: 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel',
//   PROCESSOR_LEVEL: '6',
//   PROCESSOR_REVISION: '8e0a',
//   ProgramData: 'C:\\ProgramData',
//   ProgramFiles: 'C:\\Program Files',
//   'ProgramFiles(x86)': 'C:\\Program Files (x86)',
//   ProgramW6432: 'C:\\Program Files',
//   PROMPT: '$P$G',
//   PSModulePath: 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules',
//   PUBLIC: 'C:\\Users\\Public',
//   SESSIONNAME: 'Console',
//   SystemDrive: 'C:',
//   SystemRoot: 'C:\\Windows',
//   TEMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
//   TMP: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp',
//   USERDOMAIN: 'DESKTOP-6D1598L',
//   USERDOMAIN_ROAMINGPROFILE: 'DESKTOP-6D1598L',
//   USERNAME: 'Administrator',
//   USERPROFILE: 'C:\\Users\\Administrator',
//   VSCODE_AMD_ENTRYPOINT: 'vs/workbench/api/node/extensionHostProcess',
//   VSCODE_CODE_CACHE_PATH: 'C:\\Users\\Administrator\\AppData\\Roaming\\Code\\CachedData\\252e5463d60e63238250799aef7375787f68b4ee',
//   VSCODE_CRASH_REPORTER_PROCESS_TYPE: 'extensionHost',
//   VSCODE_CWD: 'F:\\Code\\github.com\\lazyggm\\node',
//   VSCODE_HANDLES_UNCAUGHT_ERRORS: 'true',
//   VSCODE_IPC_HOOK: '\\\\.\\pipe\\9e7283c68e6159fd1e9872b65f264be5-1.78.0-main-sock',
//   VSCODE_NLS_CONFIG: '{"locale":"zh-cn","osLocale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"e8139c6a810edc38ce118d65c4ecc4ca.zh-cn","_translationsConfigFile":"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\e8139c6a810edc38ce118d65c4ecc4ca.zh-cn\\\\tcf.json","_cacheRoot":"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\e8139c6a810edc38ce118d65c4ecc4ca.zh-cn","_resolvedLanguagePackCoreLocation":"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\e8139c6a810edc38ce118d65c4ecc4ca.zh-cn\\\\252e5463d60e63238250799aef7375787f68b4ee","_corruptedFile":"C:\\\\Users\\\\Administrator\\\\AppData\\\\Roaming\\\\Code\\\\clp\\\\e8139c6a810edc38ce118d65c4ecc4ca.zh-cn\\\\corrupted.info","_languagePackSupport":true}',
//   VSCODE_PID: '18900',
//   windir: 'C:\\Windows'
// }